package com.higgsup.kpi.glossary;

public final class ErrorMessage {
    public final static String NOT_FIND_USER = "not find user";
    public final static String PARAMETERS_NAME_IS_NOT_VALID = "parameter name is not valid";
    public final static String NOT_FILLING_ALL_INFORMATION = "not filling all information";
    public final static String ALREADY_CREATED = "already created";
    public final static String GROUP_ALREADY_EXISTS = "group name already exist";
    public final static String NOT_FIND_GROUP_TYPE = "group type does not exist";
    public final static String PARAMETERS_MIN_NUMBER_OF_SESSIONS_IS_NOT_VALID = "parameter min number of sessions is not valid";
    public final static String PARAMETERS_POINT_IS_NOT_VALID = "parameter point is not valid";
    public final static String INVALIDATED_FIRST_PRIZE = "invalidated first prize score";
    public final static String INVALIDATED_SECOND_PRIZE = "invalidated second prize score";
    public final static String INVALIDATED_THIRD_PRIZE = "invalidated third prize score";
    public final static String INVALIDATED_ORGANIZERS_PRIZE = "invalidated organizer score";
    public final static String FIRST_PRIZE_NOT_LARGER_THAN_SECOND_PRIZE = "first prize score has to large than second prize score";
    public final static String SECOND_PRIZE_NOT_LARGER_THAN_THIRD_PRIZE = "second prize score has to large than third prize score";
    public final static String TEAM_BUILDING_HAS_BEEN_EXISTED = "team building activity has been existed";
    public final static String NOT_FIND_GROUP = "not find group";
    public final static String PARAMETERS_NAME_PROJECT_EXISTS = "parameters name project exist";
    public final static String PARAMETERS_ROLES_IS_EMPTY = "parameter role is empty";
    public final static String DATA_EXIST_WITH_USER_NAME = "username exists";
    public final static String NOT_FIND_ITEM = "item does not exist";
    public final static String POINT_HOST_IS_NOT_VALIDATE = "parameter point of host is not valid";
    public final static String POINT_MEMBER_IS_NOT_VALIDATE = "parameter point of member is not valid";
    public final static String POINT_LISTENER_IS_NOT_VALIDATE = "parameter point of listener is not valid";
    public final static String NOT_FIND_SEMINAR = "not find seminar";
    public final static String NAME_DOES_NOT_ALLOW_NULL = "name does not allow null";
    public final static String ERROR_IO_EXCEPTION = "error IOException";
    public final static String TEAM_BUILDING_FIRST_PRIZE_SCORE_CAN_NOT_NULL = "the first prize score can not be null";
    public final static String TEAM_BUILDING_SECOND_PRIZE_SCORE_CAN_NOT_NULL = "the second prize score can not be null";
    public final static String TEAM_BUILDING_THIRD_PRIZE_SCORE_CAN_NOT_NULL = "the third prize score can not be null";
    public final static String TEAM_BUILDING_ORGANIZERS_SCORE_CAN_NOT_NULL = "the organizer score can not be null";
    public final static String GROUP_TYPE_ID_CAN_NOT_NULL = "group type ID can not be null";
    public final static String GROUP_TYPE_CAN_NOT_NULL = "group type can not be null";
    public final static String HOST_SCORE_CAN_NOT_NULL = "host score can be not null";
    public final static String MEMBER_SCORE_CAN_NOT_NULL = "member score can be not null";
    public final static String NOT_FIND_PROJECT = "not find project by id";
    public final static String EVENT_ALREADY_EXISTS = "event name already exists";
    public final static String POINT_INFO_CAN_NOT_NULL = "point information cannot null";
    public final static String LIST_OF_PARTICIPANTS_CAN_NOT_NULL = "list of participants cannot null";
    public final static String BEGIN_DATE_CAN_NOT_NULL = "begin date cannot null";
    public final static String END_DATE_CAN_NOT_NULL = "end date cannot null";
    public final static String MEMBER_TYPE_DOES_NOT_EXIST = "member type does not exist";
}
